### ISSUE TITLE
F8 Error code

### ISSUE THREAD

**Issue by Pifftane** [nwvh/wx_carlock#2]
Hello guys, i am new at this game but i had this error code
![image](https://github.com/nwvh/wx_carlock/assets/81262513/1aeab8fc-fdc6-413f-99b6-e8eda5cbe47b)

**Comment by nwvh** [comment]
You don't have ox_lib installed...

**Comment by Pifftane** [comment]
i did it. But it  still dont work
![image](https://github.com/nwvh/wx_carlock/assets/81262513/8a77c508-7412-45fb-8bb6-cb385523a1df)
on your github stand i have to export something. How do i do this
